/**
 * Events are the only way into the core.
 *
 * Every event carries its own `at` timestamp. The core never reads a clock —
 * that rule is what lets a test advance 200 days in milliseconds, gives the
 * Daily Budget's day-keying one unambiguous definition (ADR-0011), and confines
 * the trusted-client-clock exposure ADR-0010 accepts to a single driver.
 *
 * Later specs extend this union rather than replacing it. Adding an event must
 * not require touching an existing reducer branch.
 */

/** Milliseconds since the Unix epoch, supplied by a driver. */
export type Timestamp = number;

/** A local calendar day, `YYYY-MM-DD`. Local, not UTC: the Daily Budget is a
 * claim about the user's day, not Greenwich's. */
export type LocalDate = string;

/** Supabase's user id. Opaque to the core — it never parses or generates one. */
export type UserId = string;

/**
 * The key one write is identified by, for the whole life of that write.
 *
 * Generated by a driver and carried in on the event rather than minted here: an
 * id is randomness, and the core takes randomness as an input exactly as it
 * takes time. Opaque to the core, which compares ids and never parses one.
 *
 * This is what makes at-least-once delivery safe. A retry after a dropped
 * acknowledgement carries the id the first attempt carried, so the server can
 * recognise the second delivery as the first write rather than as a second one.
 */
export type WriteId = string;

export type Identity = {
  userId: UserId;
  email: string;
};

export type SignedIn = {
  type: 'SignedIn';
  at: Timestamp;
  identity: Identity;
  /** The day the sign-in happened, per the client's clock. */
  today: LocalDate;
  /** Keys the profile write this raises. */
  writeId: WriteId;
};

export type SignedOut = {
  type: 'SignedOut';
  at: Timestamp;
};

/**
 * A day boundary crossed. Raised by the clock driver rather than derived from a
 * timestamp inside the core, so that "what day is it" has exactly one answer
 * and one place it can be wrong.
 *
 * Its first real consumer is the Daily Budget in spec #3; it ships here because
 * the rule it encodes is established here.
 */
export type DayRolled = {
  type: 'DayRolled';
  at: Timestamp;
  today: LocalDate;
};

/**
 * The user acknowledged the medical disclaimer.
 *
 * The disclaimer is load-bearing rather than ceremonial (ADR-0007): the program
 * schedules no rest, so this is where the user is told the recovery decision is
 * theirs. `at` is the acknowledgement's audit trail, which is why the event
 * carries a timestamp and not merely a flag.
 */
export type OnboardingAcknowledged = {
  type: 'OnboardingAcknowledged';
  at: Timestamp;
  /** Keys the acknowledgement write this raises. */
  writeId: WriteId;
};

/**
 * What the profile says about onboarding, reported on cold start.
 *
 * Raised by the profile driver rather than inferred from the session, because
 * "has this user acknowledged" is a fact the server holds and the client cannot
 * derive. `acknowledgedAt` is `null` for a user who genuinely has not.
 */
export type OnboardingLoaded = {
  type: 'OnboardingLoaded';
  at: Timestamp;
  acknowledgedAt: Timestamp | null;
};

/**
 * Which queued writes the server confirmed, reported by the sync driver once a
 * drain lands.
 *
 * The core learns what is durable elsewhere rather than assuming it: a write it
 * asked for is a request until this event says otherwise, which is what lets a
 * later spec show a user that a Session is still on the phone.
 *
 * Carries a list rather than one id because a drain confirms a batch, and
 * reporting them one at a time would make "the queue is empty" a state
 * assembled from several events instead of one.
 */
export type SyncAcknowledged = {
  type: 'SyncAcknowledged';
  at: Timestamp;
  /** The writes that landed, in the order the server confirmed them. */
  writeIds: readonly WriteId[];
};

/**
 * The server's snapshot, adopted on cold start.
 *
 * A cold start holds nothing the user did on another device, and the queue
 * holds only what has *not* landed — so hydrating is the one way the core
 * learns the rest. `onboardingAcknowledgedAt` is the whole snapshot for now;
 * later specs widen it rather than adding a second hydration event.
 *
 * Deliberately not a write: adopting a snapshot emits no effect, because
 * echoing the server's own answer back at it would re-stamp a row on every
 * cold start.
 */
export type RemoteStateLoaded = {
  type: 'RemoteStateLoaded';
  at: Timestamp;
  snapshot: RemoteSnapshot;
};

/** What the server holds for this user. Widened by later specs. */
export type RemoteSnapshot = {
  /** `null` is a real answer meaning the user has not acknowledged. */
  onboardingAcknowledgedAt: Timestamp | null;
};

export type CoreEvent =
  | SignedIn
  | SignedOut
  | DayRolled
  | OnboardingAcknowledged
  | OnboardingLoaded
  | SyncAcknowledged
  | RemoteStateLoaded;
